<?php
/**
 * @file
 * Code for the SR Fun and games feature.
 */

include_once 'sr_fun_and_games.features.inc';

/**
 * Implements hook_block_info().
 */
function sr_fun_and_games_block_info() {
  $blocks['fg_pledge_submission'] = array(
    'info' => t('Pledge Submission Form'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['fg_idea_generation'] = array(
    'info' => t('Idea Generation Form'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function sr_fun_and_games_block_view($delta = '') {
  $block = array('subject' => NULL);

  switch ($delta) {
    case 'fg_pledge_submission':
      $block['content']['form'] = drupal_get_form('sr_fun_and_games_pledge_submit_form');
      break;
  }
  switch ($delta) {
    case 'fg_idea_generation':
      $block['content']['form'] = drupal_get_form('sr_fun_and_games_idea_generation_form');
      break;
  }
  return $block;
}

/**
 * Pledge submission form.
 */
function sr_fun_and_games_pledge_submit_form($form, &$form_state) {

  $form['#attributes']['class'][] = 'pledge-submission-form';
  $form['#attached']['js'] = array(
    drupal_get_path('module', 'sr_fun_and_games') . '/sr-pledge-submit.js',
  );


$form['pledge'] = array(
    '#prefix' => '<h6>Brilliant! Now choose your event and add your details below.</h6>',
    '#type' => 'select',
    '#title' => 'Choose your please',
    '#default_value' => 'run',
    '#title_display' => 'invisible',
    '#grid' => 'grid-4',
    '#options' => array(
      'run' => t('Run'),
      'swim' => t('Swim'),
      'cycle' => t('Cycle'),
    ),
  );

  $form['name'] = array(
    '#type' => 'textfield',
    '#title' => t('First name'),
    '#title_display' => 'invisible',
    '#default_value' => isset($form_state['values']['name']) ? $form_state['values']['name'] : '',
    '#placeholder' => t('First name'),
    '#maxlength' => 10,
    '#size' => 25,
    '#grid' => 'grid-4 alpha',
  );

  $form['age'] = array(
    '#type' => 'textfield',
    '#title' => t('Age'),
    '#title_display' => 'invisible',
    '#default_value' => isset($form_state['values']['age']) ? $form_state['values']['age'] : '',
    '#placeholder' => t('Age'),
    '#maxlength' => 100,
    '#size' => 10,
    '#grid' => 'grid-2',
  );

  

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Add your name'),
    '#grid' => 'grid-4 omega',
    '#ajax' => array(),
    '#attributes' => array(
      'class' => array('button--large'),
    ),
  );

  $form['html'] = array(
    '#type' => 'markup',
    '#markup' => '<p id="validationmessage"></p>'
  );
  
  $form['#action'] = url('fun-and-games/fundraising-ideas-machine/add');

  return $form;
}
/**
 * Idea generation form.
 */
function sr_fun_and_games_idea_generation_form($form, &$form_state) {

  $form['#attributes']['class'][] = 'idea-generation-form';
  $form['#attached']['js'] = array(
    drupal_get_path('module', 'sr_fun_and_games') . '/sr-pledge-submit.js',
  );

  $form['pledge'] = array(
    '#type' => 'select',
    '#title' => 'Choose your pledge',
    '#default_value' => 'My own fundraising',
    '#title_display' => 'invisible',
    '#grid' => 'grid-4',
    '#options' => array(
      'freestyle' => t('My own fundraising'),
      'run' => t('Run'),
      'swim' => t('Swim'),
      'cycle' => t('Cycle'),
    ),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Generate idea'),
    '#grid' => 'grid-4 omega',
    '#ajax' => array(),
    '#attributes' => array(
      'class' => array('button--large'),
    ),
  );

  // Temporary 404 as ideas are all stored in JS for now.
  // We really don't want this to hit the server unless we can cache the request.
  // Hence no ajax views filter.
  $form['#action'] = url('404');

  return $form;
}
