<?php
/**
 * @file
 * .module file for sr16splash_kit_preorder module
 */

/**
 * Implement hook cr_webform_mq_message_insert
 *
 * Write email subscription data into ESU message queue
 *
 * @param array $message_data
 *   The $message data just written
 * @param array $webform_settings
 *   The settings linking the webform to the message queue
 * @param stdClass $submission
 *   The webform submission
 * @param MessageBrokerInterface $broker
 *   The message queue broker
 */
function sr16splash_kit_preorder_cr_webform_mq_message_insert($message_data, $webform_settings, $submission, MessageBrokerInterface $broker = NULL) {
  // The unique way to identify a webform is via its nid which is not great and not reliable
  // between environments, so the next best option is the trans_type and transSource fields
  if ($message_data['transSource'] === 'preorder' && $message_data['transType'] === 'kit') {
    if ($message_data['email_updates'] === 'yes') {

      if (!is_object($broker) || !$broker instanceof MessageBrokerInterface) {
        $broker = message_broker_get();
      }

      switch ($message_data['choose_your_fundraising_kit']) {
        case 'primary_school_fundraising_pack':
          $phase = 'PY';
          break;
        case 'secondary_school_fundraising_pack':
          $phase = 'SY';
          break;
        case 'nursery_activity_pack':
          $phase = 'EY';
          break;
        default:
          $phase = 'Unknown';
      }

      $esu_message_data = array(
        'email' => $message_data['email_address'],
        'lists' => array('general' => 'general'),
        'source' => $message_data['transSource'],
        'sourceUrl' => $message_data['transSourceURL'],
        'sendEmail' => FALSE,
        'firstName' => $message_data['first_name'],
        'phase' => $phase,
        'timestamp' => $message_data['timestamp'],
      );

      cr_marketing_prefs_subscribe(
        'marketing_general',
        $esu_message_data,
        $broker
      );
    }
  }
}
