<?php
/**
 * @file
 * Code for the Health and Training feature.
 */

include_once 'sr_health_and_training.features.inc';

function sr_health_and_training_block_info() {
  // This example comes from node.module.
  $blocks['health-quiz'] = array(
    'info' => t('Health Quiz'),
    'cache' => DRUPAL_NO_CACHE
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function sr_health_and_training_block_view($delta = '') {
  $block = array();

  $js_code = file_get_contents(drupal_get_path('module', 'sr_health_and_training') . '/js/health-training-quiz.js');
  $options = array(
    'scope' => 'header',
    'type' => 'inline',
  );

  switch ($delta) {
    case 'health-quiz':
      $block['content'] = array(
      '#markup' => '<div class="health-quiz-container background-dark">Health Quiz</div>',
      '#attached' => array(
          'js' => array(
            $js_code => $options
          ),
        ),
      );
      break;
  }

  return $block;
}
