<?php
/**
 * @file
 * Code for the SR Schools feature.
 */

include_once 'sr_schools.features.inc';

/**
 * implementation of HOOK_entity_info_alter
 */
function sr_schools_entity_info_alter(&$entity_info) {

  $entity_info['fieldable_panels_pane']['bundles']['schools_need_media'] = array(
    'label' => t('Schools Need Media'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => '/path/to/custom/icon/for/this/pane.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/schools_need_media',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}