<?php
/**
 * @file
 * Code for the rnd15 Site Media Wall feature.
 */
include_once 'rnd15_site_media_wall.features.inc';
include_once 'rnd15_site_media_wall.custom.inc';

/**
 * Implements hook_ctools_plugin_directory().
 */
function rnd15_site_media_wall_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels' && ($plugin == 'styles' || $plugin == 'layouts')) {
    return 'plugins/' . $plugin;
  }
}