<?php
/**
 * @file
 * Code for the rnd15 Donate feature.
 */

include_once 'rnd15_donate.features.inc';
include_once 'rnd15_donate.custom.inc';

/**
 * Implementation of hook_menu_alter
 *
 * The donate/worldpay/complete url is called by Worldpay when a transaction is
 * completed (successfully or cancelled).  This callback returns some content
 * to Worldpay to render on their site. By default drupal will render all page
 * regions and place the menu callback results into the main content region.
 *
 * However in this instance we don't want drupal to render and return the full
 * page, so we provide our own delivery callback function which just renders
 * the menu callback result.
 *
 * @todo In future campaigns this ought to be handled in the donate module
 * This will be tracked in the following confluence page:
 * http://confluence.comicrelief.com/pages/viewpage.action?pageId=1441869
 *
 * @param $items  array The menu_router array to alter
 */

function rnd15_donate_menu_alter(&$items) {
  $items['donate/worldpay/complete']['delivery callback'] = 'rnd15_donate_delivery_raw';
}

/**
 * Implementation of hook_form_FORM_ID_alter
 */
function rnd15_donate_form_cr_donate_donate_content_type_edit_form_alter(&$form, &$form_state) {
  $conf = $form_state['conf'];
  $form['pingit_url'] = array(
    '#title' => t('Barclays PingIt URL.'),
    '#type' => 'textfield',
    '#maxlength' => 120,
    '#description' => t('Barclays PingIt URL for off-site PingIt donations,' .
      ' please include protocol e.g: http or https prefix'),
    '#default_value' => isset($conf['pingit_url']) ? $conf['pingit_url'] : '',
  );
  $form['#submit'][]= 'rnd15_donate_donate_content_type_edit_form_submit';
}

/**
 * Implementation of hook_form_FORM_ID_alter
 */
function rnd15_donate_form_cr_donate_form_alter(&$form, &$form_state, $form_id) {
  if (!empty($form['pingit_url']['#value'])) {
    $form['pingit_url']['#type'] = 'markup';
  }
}

/**
 * Donation form configuration form submit handler
 */
function rnd15_donate_donate_content_type_edit_form_submit(&$form, &$form_state){
  $form_state['conf']['pingit_url'] = $form_state['values']['pingit_url'];
}

/**
 * Implements hook_js_alter.
 */
function rnd15_donate_js_alter(&$javascript) {
  // Remove cr_donate version of this file, as rnd15_donate.custom.parsley.js customises this for rnd15.
  unset($javascript['sites/all/modules/custom/all/cr_donate/cr_donate.validate.js']);
}