<?php

/**
 * @file
 * Install and uninstall functionality for the mediaelement module.
 */

/**
 * Implements hook_uninstall().
 */
function rnd15_site_media_uninstall() {
  variable_del('rnd15_site_media_audio_default_controls');
  variable_del('rnd15_site_media_audio_default_width');
  variable_del('rnd15_site_media_audio_default_height');
  variable_del('rnd15_site_media_audio_default_class');
  variable_del('rnd15_site_media_audio_default_download_link');
  variable_del('rnd15_site_media_audio_default_download_text');
  variable_del('rnd15_site_media_video_default_controls');
  variable_del('rnd15_site_media_video_default_width');
  variable_del('rnd15_site_media_video_default_height');
  variable_del('rnd15_site_media_video_default_class');
  variable_del('rnd15_site_media_video_default_download_link');
  variable_del('rnd15_site_media_video_default_download_text');
}
