<?php
/**
 * @file
 * Code for the What we do feature.
 */

include_once 'what_we_do.features.inc';

/**
 * implementation of HOOK_entity_info_alter
 */
function what_we_do_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['helped_people'] = array(
    'label' => t('People helped'),
    'pane top level' => FALSE, // set to true to make this show as a top level icon
    'pane icon' => '/path/to/custom/icon/for/this/pane.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/helped-people',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
