<?php
/**
 * @file
 * Code for the News Article feature.
 */

include_once 'cr_news.features.inc';


/*
 * Facebook comments based on RND13
 * Added by Jeremy P.
 */

 /**
 * Implements hook_block_info().
 */
function cr_news_block_info() {
  $blocks = array();
  $blocks['rnd-facebook-comments'] = array(
    'info' => t('Facebook comments'),
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function cr_news_block_view($delta = '') {
  $block = array();
  if ($delta == 'rnd-facebook-comments') {
    $amount = "4";
    $block = array(
      'subject' => "<none>",
      'content' => array(
        //'#prefix' => theme('fb_js'),
        '#markup' => theme('fb_comment_markup',array(
          'href' => NULL,
          'posts' => $amount)
        ),
      ),
    );
  }
  return $block;
}

/**
  * Implementation of hook_init()
  * Add Facebook SDK to body of page
  *
  */
 function cr_news_preprocess_page(&$variables) {
  // To add <head> go to
  // http://api.drupal.org/api/drupal/includes%21common.inc/function/drupal_add_html_head/7
  // if 'news article' content type add FB js
  if(arg(0) == "node" && is_numeric(arg(1)) && ($variables['node']->type == 'news_article' || $variables['node']->type == 'video')) {

    // FB Meta data
    $elements = array(
      /*
      array(
        '#tag' => 'meta',
        '#attributes' => array(
          'property' => 'fb:admins',
          'content' => '100004350964549',
        ),
      ),
      */
      array(
        '#tag' => 'meta',
        '#attributes' => array(
          'property' => 'fb:app_id',
          'content' => '527258650691001',
        ),
      ),
    );

    foreach($elements as $key => $meta_item){
      drupal_add_html_head($meta_item, 'fb_admin_' . $key);
    }

    // JS for FB JS SDK being called via drupal_add_js()
    // This is better as now this function can be cached.
    drupal_add_js(drupal_get_path('module', 'cr_news') .'/js/cr_news_facebook.js', array('weight' => '-1','group' => JS_LIBRARY));
    drupal_add_css(drupal_get_path('module', 'cr_news') .'/css/cr_news_facebook.css', array('weight' => '-1', 'group' => CSS_DEFAULT, 'every_page' => TRUE));

  }
 }

/*
 * Implements hook_preprocess_node
 */
function cr_news_preprocess_node(&$variables) {
  if($variables['type'] !== 'news_article' || $variables['view_mode'] !== 'media_bar') {
    return;
  }

  $news_flash = field_get_items('node', $variables['node'], 'field_news_flash');
  $ctas = field_get_items('node', $variables['node'], 'field_cta');

  if(!empty($news_flash) && $news_flash[0]['value']) {
    $variables['classes_array'][] = 'node-news-article__news-flash';
    $variables['node']->news_flash = TRUE;

    if(isset($variables['content']['node_link_field']) && count($ctas) > 0)  {
      
      $node_link_options = array('html'=>TRUE, 'title'=>'View full article.', 'attributes'=>array('class'=>array('node-link')));
      $node_link_title = t('<span class="text">@title</span><span class="node-link-icon"></span><span class="node-link-background"></span>', array('@title'=>$variables['title']));
      $variables['content']['node_link_field'][0]['#markup'] = l($node_link_title, $ctas[0]['url'], $node_link_options);
      if(isset($variables['content']['media_bar_read_more'])) {
        $variables['content']['media_bar_read_more'][0]['#markup'] = t('<p class="media-bar__readmore cta">@cta_title</p>', array('@cta_title' => $ctas[0]['title']));
      }
      

    }
  }
}

/**
  * Implements hook_theme()
  */
 function cr_news_theme($existing, $type, $theme, $path){
  return array(
    'fb_comment_markup'=>array(
      'variables'=>array('href'=>NULL,'posts'=>'5'),
      'function'=>'theme_fb_comment_markup',
    )
  );
 }

/**
 * Theme function for including facebook sdk in body
 *
 * @return Facebook comment markup with url to page
 */
 function theme_fb_comment_markup($variables){
  $href = $variables['href'];
  $posts = $variables['posts'];

  if($href == NULL){
    $href = url($_GET['q'], array('absolute' => true));
  }

  return "<div class=\"fb-comments\" data-href=\"{$href}\" data-num-posts=\"{$posts}\"></div>";;
 }