<?php
/**
 * @file
 * Code for the Background Images feature.
 */

include_once 'sr16splash_site_images_backgrounds.features.inc';

/*
 * Alter the pane style settings so we can extend it with match height settings
 * Implements hook_sr16splash_site_panes_inherit_grid_alter
 */
function sr16splash_site_images_backgrounds_sr16splash_site_panes_set_picture_group_alter(&$breakpoints, $context) {
  $columns = $context['columns'];
  $pane = $context['fieldable_panels_pane'];
  
  $region_settings = $pane->region_settings;
  $pane_settings = $pane->pane_settings;

  // Checks if we...
  // use backgrounds on the section
  // and have a picture group selected
  // SKIP if pane ID doesnt match the one in settings
  // THEN... loads the picture group and applies it to the image
  if(isset($region_settings['use_background_pane']) && $region_settings['use_background_pane']) {
    if($region_settings['background_pane_container']['background_pane'] != $pane->pane_id) return;
    $picture_group_id = isset($region_settings['background_pane_container']['picture_group']) ? $region_settings['background_pane_container']['picture_group'] : FALSE;
    if($picture_group_id && $picture_group_id !== '_none') {
      $picture_group = picture_mapping_load($picture_group_id);
      if(isset($picture_group->mapping)) {
        $breakpoints = $picture_group->mapping;
      }
    }
  }
}

/*
 * Alter the pane style settings so we can extend it with match height settings
 * Implements hook_form_FORM_ID_alter
 */
function sr16splash_site_images_backgrounds_form_panels_edit_style_settings_form_alter(&$form, &$form_state, $form_id) {
  // Simple check to ensure we are modifying the pane settings form and not another
  if(!isset($form['settings']['use_background_pane'])) return;

  $picture_group_options = array('_none' => 'Please select a group...');

  // Get existing groups and filter by the word focus
  $picture_groups = picture_mapping_load_all();
  foreach($picture_groups as $id => $group) {
    if(strpos($id, 'full_width')!==FALSE) {
      $picture_group_options[$id] = $group->breakpoint_group;
    }
  }

  // Create a drop down selector
  $form['settings']['background_pane_container']['picture_group'] = array(
    '#type' => 'select',
    '#title' => t('Background Pane Picture Group'),
    '#description' => t('Select the picture group you wish to apply to this background pane.'),
    '#options' => $picture_group_options,
    '#default_value' => (isset($form_state['conf']['background_pane_container']['picture_group'])) ? $form_state['conf']['background_pane_container']['picture_group'] : '_none',
  );
}