<?php
/**
 * @file
 * sr_project.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function sr_project_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => 'North East and Cumbria',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '0bf0c31c-d6c1-415e-a55f-157a50d7764d',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'West Midlands',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '1206be57-ccf2-4784-9611-fec6cd5befbc',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Yorkshire',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '15947595-22b4-4f19-97cf-40d5e13f8a65',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'East',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '1ab3f787-f41e-48ad-9f94-80a9068415f0',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'East Midlands',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '318d54fb-7be4-4b27-a672-719bab689ab3',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Northen Ireland',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '3593edfb-70ba-4365-aecd-c868212a5f4e',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'North West',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '360ef30b-37c1-4167-8346-734e76387ad8',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'London',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '54dd9c57-0fd1-42fb-a832-b5342dc10045',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'South',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '587d6752-918c-4f45-86b1-6542d7c3517d',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'South East',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '794468cb-74ed-4c65-b24e-745c3b95a2e5',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'South West',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => '9dbbb599-fd04-4f8c-8419-e53fbcfa3277',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Wales',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => 'ba90889a-1db3-4729-929b-5350b533051c',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'East Yorkshire & Lincolnshire',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => 'be67def1-8583-47d6-86be-e64df6e122b8',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'Scotland',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => 'bf2056ce-449d-4174-ab78-700ef06dbc22',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => 'West',
    'description' => '',
    'format' => 'wysiwyg',
    'weight' => 0,
    'uuid' => 'eaf3d8c8-1adb-4a2f-a395-237564f0a1b1',
    'vocabulary_machine_name' => 'project_region',
    'metatags' => array(),
  );
  return $terms;
}
