<?php
  /**
   * @file
   * Show panel panes in a region/display as a slider on Mini Panel.
   */
  /**
   * Implements hook_ctools_plugin_directory().
   */
  function rnd15_site_slideshows_ctools_plugin_directory($module, $plugin) {
    if ($module == 'panels' && ($plugin == 'styles' || $plugin == 'layouts')) {
      return 'plugins/' . $plugin;
    }
  }

  /**
   * Implements hook_panels_pre_render().
   *
   * @param $display
   */
  function rnd15_site_slideshows_panels_pre_render(&$display, $renderer) {
    $renderer->prepare();

    // Declare variables
    $panes = $renderer->prepared['panes'];
    // Get "view modes" from style settings
    $view_mode_style_settings = isset($renderer->display->panel_settings['style_settings']['default']['view_mode']) ? $renderer->display->panel_settings['style_settings']['default']['view_mode'] : null;

    // Check panel layout, only action if slideshow layout
    if(strpos('rnd15_site_slideshows_layout',$display->layout) !== FALSE)
    {
      // loop through all panes
      foreach($panes as $pane_id => $pane) {
        // check if panel "view modes" setting exist then reset all panes
        if(!empty($view_mode_style_settings)) {
          $panes[$pane_id]->configuration['view_mode'] = $view_mode_style_settings;
        }
      }
    }  

  }