; Custom CR Responsive Template
; Documentation: http://wiki.comicrelief.com/wiki/CR_Layout_V2
; Author: Jeremy P.
name = CR Responsive
description = A 12 column mobile first template with x rows.
preview = preview.png
template = cr-responsive-layout

; Regions
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer
regions[qa_mega_nav]    = QA MEGA NAV

; Stylesheets
stylesheets[all][] = css/layouts/cr-responsive/cr-responsive.layout.css
stylesheets[all][] = css/layouts/cr-responsive/cr-responsive.layout.no-query.css
