<?php
/**
 * @file
 * Code for the Partners feature.
 */

include_once 'partners.features.inc';

/**
 * implementation of HOOK_entity_info_alter
 */
function partners_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['partner'] = array(
    'label' => t('Partner'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => '/path/to/custom/icon/for/this/pane.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/partner',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}
