<?php
/**
 * @file
 * Code for the SR flash embed feature.
 */

include_once 'sr_flash_embed.features.inc';

/**
 * implementation of HOOK_entity_info_alter
 */
function sr_flash_embed_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['flash_embed'] = array(
    'label' => t('Flash Embed'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'pane icon' => '/path/to/custom/icon/for/this/pane.png',
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/flash_embed',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
 }

 function sr_flash_embed_library() {
  // Library One.
  $libraries['flash'] = array(
    'title' => 'jQuery Flash',
    'website' => 'https://github.com/Qard/jquery-flash',
    'version' => '1.3.3',
    'js' => array(
      drupal_get_path('module', 'sr_flash_embed') . '/javascripts/jquery.flash.js' => array(),
    ),
  );
  // Library Two.
  $libraries['flash-embed'] = array(
    'title' => 'Views Filter Geo',
    'version' => '1',
    'js' => array(
      drupal_get_path('module', 'sr_flash_embed') . '/javascripts/flash-embed.js' => array(),
    ),
    'dependencies' => array(
      array('sr_flash_embed', 'flash'),
    ),
  );
  return $libraries;
}

/**
 * Preprocess function for fieldable-panels-pane.tpl.php
 */
function sr_flash_embed_preprocess_fieldable_panels_pane(&$vars) {
  if($vars['elements']['#bundle'] === 'flash_embed') {
    $vars['classes_array'] = array('flash-container');
    $vars['attributes_array'] = array();

    // Using token_replace() here allows you to use useful things like [path:cdn]
    if(isset($vars['field_flash_file'])) {
      $vars['attributes_array']['data-flash-src'] = file_create_url($vars['field_flash_file'][0]['uri']);
    }

    if(isset($vars['field_width'])) {
      $vars['attributes_array']['data-flash-width'] = $vars['field_width'][0]['safe_value'];
    }

    if(isset($vars['field_height'])) {
      $vars['attributes_array']['data-flash-height'] = $vars['field_height'][0]['safe_value'];
    }

    if(isset($vars['field_flash_vars'])) {
      $vars['attributes_array']['data-flash-vars'] = token_replace($vars['field_flash_vars'][0]['safe_value']);
    }

    if(isset($vars['field_holding_image'])) {
      $vars['attributes_array']['style'] =  'background-image:url(' . file_create_url($vars['field_holding_image'][0]['uri']) . ')';
    }

    if(isset($vars['field_fallback_message'])) {
      $vars['fields'] = token_replace($vars['field_fallback_message'][0]['value']);
    } else {
      $vars['fields'] = '';
    }

    drupal_add_library('sr_flash_embed', 'flash-embed');
  }
}
