<?php

/**
 * @file sr16splash_preorder_fundraise_kit.module
 *
 * words
 *
 * Author: Andy E. Phipps
 */

function sr16splash_preprocess_webform_form(&$vars) {

 	if (isset($vars['form']['details']['nid']['#value'])) {
    $vars['nid'] = $vars['form']['details']['nid']['#value'];
  }
  else {
    $vars['nid'] = $vars['form']['submission']['#value']->nid;
  }
 	
 	// sort this out, doesn't return value properly
 	$this_title = $vars['form']['#node'];

	$this_nid = $vars['nid'];

	// Check we're looking at the right webform
	if ($this_title == "Schools Fundraising Kit" || $this_nid == 1207) {
		
		// Why doesn't this work?
		$vars['theme_hook_suggestions'][] = "webform_form__order";
  	//dpm("hooray");
		//dpm($vars);
  }
}