<?php
/**
 * @file
 * .module file for sr16splash_register_interest module
 */

/**
 * Implement hook cr_webform_mq_message_insert
 *
 * Write email subscription data into ESU message queue and fire off alternative welcome email
 *
 * @param array $message_data
 *   The $message data just written
 * @param array $webform_settings
 *   The settings linking the webform to the message queue
 * @param stdClass $submission
 *   The webform submission
 * @param MessageBrokerInterface $broker
 *   The message queue broker
 */
function sr16splash_register_interest_cr_webform_mq_message_insert($message_data, $webform_settings, $submission, MessageBrokerInterface $broker = NULL) {
  // The unique way to identify a webform is via its nid which is not great and not reliable
  // between environments, so the next best (but still not ideal) option is the trans_type and transSource fields
  if ($message_data['transSource'] === 'SR16SplashSite' && $message_data['transType'] === 'RegisterInterest') {

    // submitting this form should trigger an implicit email sign up so write message to ESU queue
    if (!is_object($broker) || !$broker instanceof MessageBrokerInterface) {
      $broker = message_broker_get();
    }

    $esu_message_data = array(
      'email'     => $message_data['email_address'] ?: 'unknown',
      'lists'     => array('general' => 'general'),
      'source'    => $message_data['transSource']  ?: 'unknown',
      'sourceUrl' => $message_data['transSourceURL']  ?: 'unknown',
      'sendEmail' => FALSE,
      'firstName' => $message_data['first_name']  ?: 'unknown',
      'timestamp' => $message_data['timestamp']  ?: REQUEST_TIME,
    );

    // We don't want to trigger the normal transactional welcome email here.
    // This is avoided by passing something other than "marketing_general" as the first param here
    cr_marketing_prefs_subscribe('', $esu_message_data, $broker);

    // Send welcome email
    // Not ideal to have hardcoded email ids here, but this is for a temporary site
    // and there is no foreseeable reason we should need to switch to a different
    // welcome email rather than edit the existing one
    $email_unique = '3474A13F13404347';
    $email_security = 'EdX7CqkmlKBa8SA9MOPQIevULEt-bazAjDnef6kyW8TeKPs';
    cr_transaction_emails_send(
      $message_data['email_address'],
      $email_unique,
      $email_security,
      $message_data['transSource']);
  }
}
