<?php
/**
 * @file
 * sr16splash_site_images.default_picture_mapping.inc
 */

/**
 * Implements hook_default_picture_mapping().
 */
function sr16splash_site_images_default_picture_mapping() {
  $export = array();

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_1';
  $picture_mapping->breakpoint_group = 'col_1';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_1_xs',
      '2x' => 'col_1_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_1_sm',
      '2x' => 'col_1_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_1_md',
      '2x' => 'col_1_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_1_lg',
      '2x' => 'col_1_lg_2x',
    ),
  );
  $export['col_1'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_2';
  $picture_mapping->breakpoint_group = 'col_2';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_2_xs',
      '2x' => 'col_2_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_2_sm',
      '2x' => 'col_2_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_2_md',
      '2x' => 'col_2_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_2_lg',
      '2x' => 'col_2_lg_2x',
    ),
  );
  $export['col_2'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_3';
  $picture_mapping->breakpoint_group = 'col_3';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_3_xs',
      '2x' => 'col_3_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_3_sm',
      '2x' => 'col_3_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_3_md',
      '2x' => 'col_3_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_3_lg',
      '2x' => 'col_3_lg_2x',
    ),
  );
  $export['col_3'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_4';
  $picture_mapping->breakpoint_group = 'col_4';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_4_xs',
      '2x' => 'col_4_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_4_sm',
      '2x' => 'col_4_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_4_md',
      '2x' => 'col_4_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_4_lg',
      '2x' => 'col_4_lg_2x',
    ),
  );
  $export['col_4'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_5';
  $picture_mapping->breakpoint_group = 'col_5';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_5_xs',
      '2x' => 'col_5_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_5_sm',
      '2x' => 'col_5_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_5_md',
      '2x' => 'col_5_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_5_lg',
      '2x' => 'col_5_lg_2x',
    ),
  );
  $export['col_5'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_6';
  $picture_mapping->breakpoint_group = 'col_6';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_6_xs',
      '2x' => 'col_6_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_6_sm',
      '2x' => 'col_6_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_6_md',
      '2x' => 'col_6_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_6_lg',
      '2x' => 'col_6_lg_2x',
    ),
  );
  $export['col_6'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_7';
  $picture_mapping->breakpoint_group = 'col_7';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_7_xs',
      '2x' => 'col_7_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_7_sm',
      '2x' => 'col_7_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_7_md',
      '2x' => 'col_7_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_7_lg',
      '2x' => 'col_7_lg_2x',
    ),
  );
  $export['col_7'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_8';
  $picture_mapping->breakpoint_group = 'col_8';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_8_xs',
      '2x' => 'col_8_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_8_sm',
      '2x' => 'col_8_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_8_md',
      '2x' => 'col_8_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_8_lg',
      '2x' => 'col_8_lg_2x',
    ),
  );
  $export['col_8'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_9';
  $picture_mapping->breakpoint_group = 'col_9';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_9_xs',
      '2x' => 'col_9_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_9_sm',
      '2x' => 'col_9_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_9_md',
      '2x' => 'col_9_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_9_lg',
      '2x' => 'col_9_lg_2x',
    ),
  );
  $export['col_9'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_10';
  $picture_mapping->breakpoint_group = 'col_10';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_10_xs',
      '2x' => 'col_10_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_10_sm',
      '2x' => 'col_10_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_10_md',
      '2x' => 'col_10_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_10_lg',
      '2x' => 'col_10_lg_2x',
    ),
  );
  $export['col_10'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_11';
  $picture_mapping->breakpoint_group = 'col_11';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_11_xs',
      '2x' => 'col_11_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_11_sm',
      '2x' => 'col_11_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_11_md',
      '2x' => 'col_11_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_11_lg',
      '2x' => 'col_11_lg_2x',
    ),
  );
  $export['col_11'] = $picture_mapping;

  $picture_mapping = new stdClass();
  $picture_mapping->disabled = FALSE; /* Edit this to true to make a default picture_mapping disabled initially */
  $picture_mapping->api_version = 1;
  $picture_mapping->machine_name = 'col_12';
  $picture_mapping->breakpoint_group = 'col_12';
  $picture_mapping->mapping = array(
    'breakpoints.theme.cr_layout_v2.xs' => array(
      '1x' => 'col_12_xs',
      '2x' => 'col_12_xs_2x',
    ),
    'breakpoints.theme.cr_layout_v2.sm' => array(
      '1x' => 'col_12_sm',
      '2x' => 'col_12_sm_2x',
    ),
    'breakpoints.theme.cr_layout_v2.md' => array(
      '1x' => 'col_12_md',
      '2x' => 'col_12_md_2x',
    ),
    'breakpoints.theme.cr_layout_v2.lg' => array(
      '1x' => 'col_12_lg',
      '2x' => 'col_12_lg_2x',
    ),
  );
  $export['col_12'] = $picture_mapping;

  return $export;
}
