<?php

// timestamp 1395360000 is Fri 21/03/2014 00:00:00

function sr_front_countdown_init() {

  if(drupal_is_front_page()) {

    // Add Countdown CSS
    drupal_add_css(drupal_get_path('module', 'sr_front_countdown') . '/css/flipclock.css', 'file');

    // Add FlipBoard JS library
    drupal_add_js(drupal_get_path('module', 'sr_front_countdown') . '/libraries/flipclock/libs/base.js', 'file');
    drupal_add_js(drupal_get_path('module', 'sr_front_countdown') . '/libraries/flipclock/flipclock.js', 'file');
    drupal_add_js(drupal_get_path('module', 'sr_front_countdown') . '/libraries/flipclock/faces/dailycounter.js', 'file');

    drupal_add_js(drupal_get_path('module', 'sr_front_countdown') . '/js/sr_countdown.js', 'file');

  }

}

function _countdown_furniture($timestamp = '1395360000') {

  $event = $timestamp;

  $countdownDays = round(($event - time())/86400);

  // If $countdownDays is 0 then it means that it is actually up to 1 day away
  // e.g. 8 hours 4 mins 20 secs is still 1 day away but we do not display
  // this granular time information so we falsify that it is 1 day away.
  if($countdownDays == 0) {
    $countdownDays = 1;
  }

  $html = '';

  // create a flipclock-custom-false-face for every char of $countdownDays
  foreach(str_split($countdownDays) as $val => $digit) {
    $html .= '<div class="flip-clock-custom-false-face">' . $digit . '</div>';
  }

  // @return array of rendered HTML and days
  return array('html' => $html, 'days' => $countdownDays);

}

function sr_front_countdown_block_view($delta = '') {
  $block = array();

  $sportReliefTimestamp = variable_get('countdown_timestamp', 1395360000);
  $countdownFurniture = _countdown_furniture($sportReliefTimestamp);

  $countdownHTML = '<div class="countdown-offline clearfix"><span>Only</span>';
  $countdownHTML .= $countdownFurniture['html'];
  $countdownHTML .= '<span class="countdown-offline-text-last">';
    $countdownHTML .= ($countdownFurniture['days'] == 1 ? 'day' : 'days');
    $countdownHTML .= ' to go!';
  $countdownHTML .= '</span>';
  $countdownHTML .= '</div>';
  $countdownHTML .= '<div class="countdown" data-future-timestamp="' . variable_get('countdown_timestamp', 1395360000) . '"></div>';

  switch ($delta) {
    case 'sr_front_countdown':
      $block['subject'] = '';
      $block['content'] = $countdownHTML;
    break;
  }

  return $block;
}

function sr_front_countdown_block_info() {

  $blocks['sr_front_countdown'] = array(
    'info' => t('Countdown to SportRelief'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

function sr_front_countdown_config_form($form, &$form_state) {

  drupal_set_title("Configure SportRelief.com Countdown Timer");

  $form['countdown_timestamp'] = array(
    '#type' => 'textfield',
    '#title' => t('Countdown to this timestamp'),
    '#default_value' => variable_get('countdown_timestamp', 1395360000),
    '#size' => 20,
    '#maxlength' => 20,
    '#description' => t('Enter a UNIX timestamp'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

function sr_front_countdown_menu() {
  $items = array();
  $items['admin/config/content/sr_front_countdown_config'] = array(
    'title' => 'SportRelief.com Countdown',
    'type' => MENU_LOCAL_TASK,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sr_front_countdown_config_form'),
    'access arguments' => array('administer site configuration'),
  );
  return $items;
}
