<?php
/**
 * @file sr16splash_site_tabs.module
 *
 * Show panel panes in a region/display as a tab on Mini Panel.
 *
 * Author: Andy E. Phipps
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
  
function sr16splash_site_tabs_ctools_plugin_directory($module, $plugin) {
  if ($module == 'panels' && ($plugin == 'styles' || $plugin == 'layouts')) {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_panels_pre_render().
 *
 * @param $display
 */
function sr16splash_site_tabs_panels_pre_render(&$display, $renderer) {
  $renderer->prepare();
 
  // Declare variables
  $panes = $renderer->prepared['panes'];

  // Get "view modes" from style settings
  $view_mode_style_settings = isset($renderer->display->panel_settings['style_settings']['default']['view_mode']) ? $renderer->display->panel_settings['style_settings']['default']['view_mode'] : null;

  // Check panel layout, only continue if pane uses site tabs layout
  if(strpos('sr16splash_site_tabs',$display->layout) !== FALSE) {
    // loop through all panes
    foreach($panes as $pane_id => $pane) {
      // check if panel "view modes" setting exist then reset all panes
      if(!empty($view_mode_style_settings)) {
        $panes[$pane_id]->configuration['view_mode'] = $view_mode_style_settings;
      }
    }
  }  
}